#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "photoprism"
name = "Photoprism"
description.en = "AI-Powered Photos App for the Decentralized Web"
description.gl = "App de Fotos con tecnoloxía IA para a Web Descentralizada"
description.ca = "Aplicació de fotografia amb IA per la web descentralitzada"
description.fr = "Gestion de photos en ligne"

version = "2025.04.26~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0-only"
website = "https://photoprism.app"
demo = "https://demo-fr.photoprism.app"
admindoc = "https://docs.photoprism.app/developer-guide/"
userdoc = "https://docs.photoprism.app/user-guide/"
code = "https://github.com/photoprism/photoprism"
fund = "https://www.photoprism.app/membership"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/photoprism"

    [install.init_main_permission]
    help.en = "If enabled, Photoprism will be accessible by mobile apps and by users without a YunoHost account. This can be changed later in the webadmin."
    help.gl = "Se está activado, Photoprism será accesible para apps móbiles e usuarias sen unha conta YunoHost. Podes cambiar isto máis tarde nos axustes de administración."
    help.ca = "Si ho activeu, Photoprism serà accessible amb aplicacions mòbil i per usuaris sense compte a YunoHost. Es pot canviar més tard a la web d'administració."
    help.fr = "Si cette case est cochée, Photoprism sera accessible par des applications mobiles et par les utilisateurs n’ayant pas de compte YunoHost. Vous pourrez changer cela dans la webadmin."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.gl = "Elixe o idioma da aplicación"
    ask.ca = "Triar l'idioma de l'aplicació"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Photoprism currently supports only one user : admin. Choose a password here."
    help.gl = "Actualmente Photoprism só ten soporte para unha usuaria: admin. Escribe aquí o seu contrasinal."
    help.ca = "Photoprism només permet un únic usuari de moment: admin. Trieu-ne la contrasenya aquí."
    help.fr = "Photoprism ne permet qu'un seul utilisateur pour le moment. Choisissez un mot de passe ici."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/photoprism/photoprism/releases/download/250426-27ec7a128/photoprism_250426-27ec7a128-linux-amd64.tar.gz"
    amd64.sha256 = "8d113bf3ee048e33bb426df4f8125d37dafd480ee51c66a4f67d79714e21c290"

    arm64.url = "https://github.com/photoprism/photoprism/releases/download/250426-27ec7a128/photoprism_250426-27ec7a128-linux-arm64.tar.gz"
    arm64.sha256 = "14c9bb7368d6aa56c9c05cb58e6bbdb4fad1616b9f21ff03fc7f147a3e82323e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "([0-9]{2})([0-9]{2})([0-9]{2})"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.arm64 = ".*arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    sharing.url = "/s"
    sharing.allowed = "visitors"
    sharing.show_tile = false
    sharing.protected = true

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "exiftool",
        "darktable",
        "rawtherapee",
        "imagemagick",
        "libvips42",
        "libjxl-tools",
        "ffmpeg",
        "sqlite3",
        "tzdata",
        "libc6-dev",
        "libssl-dev",
        "libxft-dev",
        "libhdf5-serial-dev",
        "libpng-dev",
        "libheif-examples",
        "librsvg2-bin",
        "libx264-dev",
        "libx265-dev",
        "libnss3",
        "libfreetype6",
        "libfreetype6-dev",
        "libfontconfig1",
        "libfontconfig1-dev",
        "libzmq3-dev",
        "libimage-exiftool-perl",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
