#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If language_key doesn't exist, create it
if [ -z "${language_key:-}" ]; then
        language_key=$(ynh_app_setting_get --key=language)
	ynh_app_setting_set --key=language_key --value=$language_key
	ynh_app_setting_delete --key=language
fi

if [ -z "${admin:-}" ]; then
	admin="admin"
	ynh_app_setting_set --app=$app --key=admin --value=$admin
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# UPDATE DATA DIRECTORY
#=================================================
ynh_script_progression "Updating data directory..."

# assets location has changed to the $install_dir
ynh_secure_remove $data_dir/assets

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"

#=================================================
# RUNNNING DB MIGRATIONS
#=================================================
ynh_script_progression --message="Running database migrations..."

if ynh_compare_current_package_version --comparison lt --version 2024.05.31~ynh1
then
    ynh_exec_warn_less $install_dir/bin/photoprism \
		--assets-path=$install_dir/assets \
		--originals-path=/home/yunohost.app/photoprism/photos/originals \
		--import-path=/home/yunohost.app/photoprism/photos/import users reset --yes
fi

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add_systemd

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

ynh_config_add_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="AI-Powered Photos App for the Decentralized Web" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_hide_warnings ynh_systemctl --service="${app}" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Started AI-Powered Photos App for the Decentralized Web"

sleep 30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
